name: Generate Hit Scores

on:
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Hit Score script
        run: python hit_score.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hit_scores.json
          git commit -m "Update hit scores [skip ci]" || echo "No changes to commit"
          git push
