name: Generate Hit Scores

on:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # ✅ Needed for push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run Hit Score script
        run: python hit_score.py

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add hit_scores.json
          git commit -m "Update hit_scores.json [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
